# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-30 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190619_1402'),
    ]

    operations = [

    ]
