# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-01 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_email_active'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='email_active',
        #     field=models.BooleanField(default=False, verbose_name='email status'),
        # ),
    ]
