# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
